//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalApp
{
    using System;
    
    
    public sealed class EvergineContent
    {
        
        public sealed class Environments
        {
            
            /// <summary> Asset Path (Environments/Skybox.wemt) </summary>
            public static readonly Guid Skybox = new Guid("bcad3070-d8ed-4c2f-88e7-322527b1b11a");
            
            /// <summary> Asset Path (Environments/WhiteRoom.png.wetx) </summary>
            public static readonly Guid WhiteRoom_png = new Guid("102292ae-a4e2-46be-aa6c-0b7e4a91fbd1");
        }
        
        public sealed class Materials
        {
            
            /// <summary> Asset Path (Materials/BlueMat.wemt) </summary>
            public static readonly Guid BlueMat = new Guid("fd599249-5405-4cf0-b950-5573dd037b3b");
            
            /// <summary> Asset Path (Materials/ShadowMat.wemt) </summary>
            public static readonly Guid ShadowMat = new Guid("cf7aa4cd-fcec-48ee-a51f-7a60fb55aee8");
            
            /// <summary> Asset Path (Materials/DefaultMaterial.wemt) </summary>
            public static readonly Guid DefaultMaterial = new Guid("02181b63-5a0e-46d1-9208-d92376ae33fb");
            
            /// <summary> Asset Path (Materials/DistortionMat.wemt) </summary>
            public static readonly Guid DistortionMat = new Guid("5f795365-07f5-4b56-83df-043eb40a7457");
        }
        
        public sealed class Models
        {
            
            /// <summary> Asset Path (Models/tesla_model_3.glb.wemd) </summary>
            public static readonly Guid tesla_model_3_glb = new Guid("e164b6ee-73b2-419c-8253-0bc99f8501b4");
            
            public sealed class tesla_model_3_Embedded
            {
                
                public sealed class Materials
                {
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/CAR_PAINT.wemt) </summary>
                    public static readonly Guid CAR_PAINT = new Guid("9249e9fe-ba0d-4e69-9e9c-0f429a3ee913");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/chrome.wemt) </summary>
                    public static readonly Guid chrome = new Guid("329f806d-b5d5-4d2f-8686-623d8b42e8c5");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/Glass.wemt) </summary>
                    public static readonly Guid Glass = new Guid("941fd088-8d0f-46d7-8d72-544b7020ca50");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/LED_PHARE.wemt) </summary>
                    public static readonly Guid LED_PHARE = new Guid("5853c5f5-8968-4af3-b1d4-a1934c35d909");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/Material_001.wemt) </summary>
                    public static readonly Guid Material_001 = new Guid("eea581b9-64a2-4871-9e14-6aae912ccbb5");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/Material_002.wemt) </summary>
                    public static readonly Guid Material_002 = new Guid("24ba6488-66aa-4630-87a7-bbe514ae5c83");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/Material_003.wemt) </summary>
                    public static readonly Guid Material_003 = new Guid("ef840173-c295-453c-a09b-07586a1f517e");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/Material_004.wemt) </summary>
                    public static readonly Guid Material_004 = new Guid("1baeb07f-41e0-44ed-a812-6cfc75a172f1");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/Material_005.wemt) </summary>
                    public static readonly Guid Material_005 = new Guid("ddd411b7-7964-46c3-a01e-e51505ec8093");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/Material_007.wemt) </summary>
                    public static readonly Guid Material_007 = new Guid("5f1ebce5-2f88-45b9-a036-9c29eeaf0fc5");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/Material_008.wemt) </summary>
                    public static readonly Guid Material_008 = new Guid("493ec39b-ad75-4970-a7f4-2fe769c4441e");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/Material_009.wemt) </summary>
                    public static readonly Guid Material_009 = new Guid("744dfcf8-63c6-4578-8cfa-aa9feb39430f");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/Material_010.wemt) </summary>
                    public static readonly Guid Material_010 = new Guid("6882df89-2278-44b1-8c04-54d533901fe4");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/Material_011.wemt) </summary>
                    public static readonly Guid Material_011 = new Guid("00870553-33e8-4fe9-bc9c-6175f60978de");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/Material_012.wemt) </summary>
                    public static readonly Guid Material_012 = new Guid("7ea99b5e-d983-44f8-a6c4-031f50218458");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/Material_013.wemt) </summary>
                    public static readonly Guid Material_013 = new Guid("aac774fd-b48c-47be-98a0-c3c7f06dec53");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/Material_014.wemt) </summary>
                    public static readonly Guid Material_014 = new Guid("1ebb2702-33a7-4015-84c8-4d599afed62a");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/Material_015.wemt) </summary>
                    public static readonly Guid Material_015 = new Guid("7c215cd3-c1b9-44e1-a0fa-375d321fbb6c");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/Material_016.wemt) </summary>
                    public static readonly Guid Material_016 = new Guid("708c4ccd-9b29-4449-ac15-224582587fbf");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/Material_017.wemt) </summary>
                    public static readonly Guid Material_017 = new Guid("55884fc3-cdab-4a99-b672-8fc4bc1193de");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Materials/PLASTIC.wemt) </summary>
                    public static readonly Guid PLASTIC = new Guid("39ec482a-86d3-476a-932a-7ff68f880c3c");
                }
                
                public sealed class Samplers
                {
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Samplers/Sampler0.wesp) </summary>
                    public static readonly Guid Sampler0 = new Guid("c408aa08-641f-4405-9d6f-6d52606af35b");
                }
                
                public sealed class Textures
                {
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Textures/tesla_model_3_0.png.wetx) </summary>
                    public static readonly Guid tesla_model_3_0_png = new Guid("cadde534-4ce0-4449-ab6b-7b4e19c7da79");
                    
                    /// <summary> Asset Path (Models/tesla_model_3_Embedded/Textures/tesla_model_3_1.png.wetx) </summary>
                    public static readonly Guid tesla_model_3_1_png = new Guid("c243bf49-7deb-4652-90af-2ee74421a9c5");
                }
            }
        }
        
        public sealed class Scenes
        {
            
            /// <summary> Asset Path (Scenes/MyScene.wescene.wesc) </summary>
            public static readonly Guid MyScene_wescene = new Guid("eff3fd23-ea05-4182-b7d7-e7f9b50a8064");
        }
        
        public sealed class Textures
        {
            
            /// <summary> Asset Path (Textures/CarShadow.png.wetx) </summary>
            public static readonly Guid CarShadow_png = new Guid("8f005737-3665-4a1d-a766-a5e9d6c8b0fc");
            
            /// <summary> Asset Path (Textures/Checker.png.wetx) </summary>
            public static readonly Guid Checker_png = new Guid("8b1d459c-c433-4ee3-bfe5-b45fbce12736");
            
            /// <summary> Asset Path (Textures/dfgLut.png.wetx) </summary>
            public static readonly Guid dfgLut_png = new Guid("d81d459c-c433-4ee3-bfe5-b45fbce12736");
            
            /// <summary> Asset Path (Textures/particle.png.wetx) </summary>
            public static readonly Guid particle_png = new Guid("01221b69-9685-4f0d-9862-6be704bd3cd2");
            
            public sealed class PostProcessing
            {
                
                /// <summary> Asset Path (Textures/PostProcessing/BlueNoise.png.wetx) </summary>
                public static readonly Guid BlueNoise_png = new Guid("85459c5f-78da-4ed0-9038-26d2dd27280d");
                
                /// <summary> Asset Path (Textures/PostProcessing/DistortionTexture.png.wetx) </summary>
                public static readonly Guid DistortionTexture_png = new Guid("34b16253-37ce-457a-bd5b-3ed27bb51738");
                
                /// <summary> Asset Path (Textures/PostProcessing/FlareGradient.png.wetx) </summary>
                public static readonly Guid FlareGradient_png = new Guid("1104127f-8a0e-4a1c-9b8c-b8832362a809");
                
                /// <summary> Asset Path (Textures/PostProcessing/FlareStarburst.png.wetx) </summary>
                public static readonly Guid FlareStarburst_png = new Guid("385d88a2-9a0c-4275-ac7d-499207f1bae0");
                
                /// <summary> Asset Path (Textures/PostProcessing/LensDirt00.png.wetx) </summary>
                public static readonly Guid LensDirt00_png = new Guid("75a8073c-1878-4160-a92d-da0d7530cbb6");
            }
        }
        
        public sealed class Computes
        {
            
            public sealed class Environment
            {
                
                /// <summary> Asset Path (Computes/Environment/AtmosphereCompute.wefx) </summary>
                public static readonly Guid AtmosphereCompute = new Guid("df2ab68e-2005-4a33-af58-1f9bcf68fe27");
                
                /// <summary> Asset Path (Computes/Environment/IrradianceCompute.wefx) </summary>
                public static readonly Guid IrradianceCompute = new Guid("0a86c4bc-1891-4776-8971-04f894169bc1");
                
                /// <summary> Asset Path (Computes/Environment/RadianceCompute.wefx) </summary>
                public static readonly Guid RadianceCompute = new Guid("d0cd29fb-701e-4e2e-b6af-d9d138675e06");
            }
            
            public sealed class Morphing
            {
                
                /// <summary> Asset Path (Computes/Morphing/MorphingCompute.wefx) </summary>
                public static readonly Guid MorphingCompute = new Guid("d70ae5dc-18df-465b-bab4-809db43cdd3b");
            }
            
            public sealed class Particles
            {
                
                /// <summary> Asset Path (Computes/Particles/DragCompute.wefx) </summary>
                public static readonly Guid DragCompute = new Guid("459b0457-9b93-497a-80f4-db97623a0c2b");
                
                /// <summary> Asset Path (Computes/Particles/ParticleCompute.wefx) </summary>
                public static readonly Guid ParticleCompute = new Guid("eaab0be8-80fc-47c8-8fc1-06bf5920ac7a");
                
                /// <summary> Asset Path (Computes/Particles/PointAttractorCompute.wefx) </summary>
                public static readonly Guid PointAttractorCompute = new Guid("f79873b0-80c4-49ef-b7ae-2044b59c5324");
                
                /// <summary> Asset Path (Computes/Particles/WindCompute.wefx) </summary>
                public static readonly Guid WindCompute = new Guid("978f10dc-0465-4f34-b55d-cb66e833e400");
            }
            
            public sealed class PostProcessing
            {
                
                /// <summary> Asset Path (Computes/PostProcessing/AMDSharpen.wefx) </summary>
                public static readonly Guid AMDSharpen = new Guid("d63a912d-a948-4396-b8f8-6e668c2d4cfe");
                
                /// <summary> Asset Path (Computes/PostProcessing/AMDSuperResolution.wefx) </summary>
                public static readonly Guid AMDSuperResolution = new Guid("5541769a-3957-452d-856e-c33ba640c047");
                
                /// <summary> Asset Path (Computes/PostProcessing/AutoDepthBounds.wefx) </summary>
                public static readonly Guid AutoDepthBounds = new Guid("d9736e8c-45e9-4cb4-97ab-a671b03b59b1");
                
                /// <summary> Asset Path (Computes/PostProcessing/BilateralBlur.wefx) </summary>
                public static readonly Guid BilateralBlur = new Guid("7af338ce-d619-4ea9-90d3-a37638c00f77");
                
                /// <summary> Asset Path (Computes/PostProcessing/Blend.wefx) </summary>
                public static readonly Guid Blend = new Guid("eaa0fbbb-3923-4a8d-9a4b-c5ac569a30c1");
                
                /// <summary> Asset Path (Computes/PostProcessing/Bloom.wefx) </summary>
                public static readonly Guid Bloom = new Guid("f2bd0fb3-fe4a-4589-88a2-c6f985fa434f");
                
                /// <summary> Asset Path (Computes/PostProcessing/BloomThreshold.wefx) </summary>
                public static readonly Guid BloomThreshold = new Guid("5c805d88-78de-4f25-b2b8-40c45a54a344");
                
                /// <summary> Asset Path (Computes/PostProcessing/BokehBlur.wefx) </summary>
                public static readonly Guid BokehBlur = new Guid("0aea5c88-be16-4260-99c3-f92746d9ca72");
                
                /// <summary> Asset Path (Computes/PostProcessing/BokehCoCDownscale.wefx) </summary>
                public static readonly Guid BokehCoCDownscale = new Guid("4e1cc8ff-0b41-4964-a558-efcf4200f143");
                
                /// <summary> Asset Path (Computes/PostProcessing/BokehCombine.wefx) </summary>
                public static readonly Guid BokehCombine = new Guid("6990cd81-4fde-40c8-a4bf-4ef8871dac2f");
                
                /// <summary> Asset Path (Computes/PostProcessing/BokehExtractFields.wefx) </summary>
                public static readonly Guid BokehExtractFields = new Guid("d745fa1a-13d0-4547-8e68-ac04f491581e");
                
                /// <summary> Asset Path (Computes/PostProcessing/BokehNearBorder.wefx) </summary>
                public static readonly Guid BokehNearBorder = new Guid("9c96630f-c22f-44dc-b347-ad11aaea95ef");
                
                /// <summary> Asset Path (Computes/PostProcessing/BokehNearHalo.wefx) </summary>
                public static readonly Guid BokehNearHalo = new Guid("7ab68877-e067-4eda-8293-8179d020102d");
                
                /// <summary> Asset Path (Computes/PostProcessing/CameraMotionBlur.wefx) </summary>
                public static readonly Guid CameraMotionBlur = new Guid("f5e59513-0d6f-4051-9331-586ccd951ef3");
                
                /// <summary> Asset Path (Computes/PostProcessing/DownSample.wefx) </summary>
                public static readonly Guid DownSample = new Guid("8681008a-73c9-4337-96da-e081b4dff24d");
                
                /// <summary> Asset Path (Computes/PostProcessing/Enabled.wefx) </summary>
                public static readonly Guid Enabled = new Guid("3fc3ec67-408d-4795-a1b5-5e198fbc24af");
                
                /// <summary> Asset Path (Computes/PostProcessing/Fog.wefx) </summary>
                public static readonly Guid Fog = new Guid("37886c87-58a8-408e-a53c-d851fde2f383");
                
                /// <summary> Asset Path (Computes/PostProcessing/FXAA.wefx) </summary>
                public static readonly Guid FXAA = new Guid("d5577c1c-52e0-4071-a1bd-928339880bc3");
                
                /// <summary> Asset Path (Computes/PostProcessing/Gaussian.wefx) </summary>
                public static readonly Guid Gaussian = new Guid("b1053619-59d0-4ea4-ba62-b7c85716c117");
                
                /// <summary> Asset Path (Computes/PostProcessing/Histogram.wefx) </summary>
                public static readonly Guid Histogram = new Guid("d743adde-eb54-4f0b-8bc3-e431a34f762d");
                
                /// <summary> Asset Path (Computes/PostProcessing/IsolatingSky.wefx) </summary>
                public static readonly Guid IsolatingSky = new Guid("83489f84-2293-4dd6-bce0-5a479f533fc9");
                
                /// <summary> Asset Path (Computes/PostProcessing/LensFlare.wefx) </summary>
                public static readonly Guid LensFlare = new Guid("120f7347-14bc-423c-8d37-65ee4e32e0dd");
                
                /// <summary> Asset Path (Computes/PostProcessing/LightShaft.wefx) </summary>
                public static readonly Guid LightShaft = new Guid("347a536f-f394-4ea7-b32c-0ff81598eedd");
                
                /// <summary> Asset Path (Computes/PostProcessing/LuminanceAvg.wefx) </summary>
                public static readonly Guid LuminanceAvg = new Guid("d7cba48c-3058-4386-9a0a-27bf8925bfaf");
                
                /// <summary> Asset Path (Computes/PostProcessing/Mediam.wefx) </summary>
                public static readonly Guid Mediam = new Guid("fc650ac8-a6df-4f36-b9fc-55759cd5d811");
                
                /// <summary> Asset Path (Computes/PostProcessing/ReconstructFromDepth.wefx) </summary>
                public static readonly Guid ReconstructFromDepth = new Guid("ed92c3b2-44a0-4592-8d8e-e48ca4de92e4");
                
                /// <summary> Asset Path (Computes/PostProcessing/Sharpen.wefx) </summary>
                public static readonly Guid Sharpen = new Guid("5df13f05-a063-420e-a506-59ed04203d70");
                
                /// <summary> Asset Path (Computes/PostProcessing/SSAO.wefx) </summary>
                public static readonly Guid SSAO = new Guid("5c884db4-9e59-4a00-8e17-62487eef9937");
                
                /// <summary> Asset Path (Computes/PostProcessing/SSR.wefx) </summary>
                public static readonly Guid SSR = new Guid("e6a559e1-c8f7-4729-b36d-85a2ecb63ad5");
                
                /// <summary> Asset Path (Computes/PostProcessing/SSRResolve.wefx) </summary>
                public static readonly Guid SSRResolve = new Guid("71506dd4-43b7-4e35-8d0c-a16cc7237083");
                
                /// <summary> Asset Path (Computes/PostProcessing/TAA.wefx) </summary>
                public static readonly Guid TAA = new Guid("b4fdb094-d620-4252-b523-aa5182745b32");
                
                /// <summary> Asset Path (Computes/PostProcessing/ToneMapping.wefx) </summary>
                public static readonly Guid ToneMapping = new Guid("c0529ee7-8b51-45f2-aa39-8167614dc8af");
            }
            
            public sealed class Skinning
            {
                
                /// <summary> Asset Path (Computes/Skinning/SkinningCompute.wefx) </summary>
                public static readonly Guid SkinningCompute = new Guid("c5af55c9-063d-49c7-bb65-aa31062251a2");
            }
        }
        
        public sealed class Effects
        {
            
            /// <summary> Asset Path (Effects/AtmosphericEffect.wefx) </summary>
            public static readonly Guid AtmosphericEffect = new Guid("d551eb2b-202d-454d-a059-c3ddce284636");
            
            /// <summary> Asset Path (Effects/AtmosphericQuadEffect.wefx) </summary>
            public static readonly Guid AtmosphericQuadEffect = new Guid("d68b16ac-1b98-4b1a-95f6-eb39a41b70ec");
            
            /// <summary> Asset Path (Effects/BackgroundImageEffect.wefx) </summary>
            public static readonly Guid BackgroundImageEffect = new Guid("5d9b7441-7fcd-4167-9dd4-05e6dce235e7");
            
            /// <summary> Asset Path (Effects/BillboardEffect.wefx) </summary>
            public static readonly Guid BillboardEffect = new Guid("dbb1f60a-82ad-40fc-8fbb-7b85caa6de0a");
            
            /// <summary> Asset Path (Effects/DistortionEffect.wefx) </summary>
            public static readonly Guid DistortionEffect = new Guid("d672019c-2887-4056-a0e7-2141d2fe5f78");
            
            /// <summary> Asset Path (Effects/LineBatchEffect.wefx) </summary>
            public static readonly Guid LineBatchEffect = new Guid("dcb1f60a-82ad-40fc-8fbb-7b85caa6de0a");
            
            /// <summary> Asset Path (Effects/LineEffect.wefx) </summary>
            public static readonly Guid LineEffect = new Guid("ddb1f60a-82ad-40fc-8fbb-7b85caa6de0a");
            
            /// <summary> Asset Path (Effects/ParticlesEffect.wefx) </summary>
            public static readonly Guid ParticlesEffect = new Guid("5d0ed39b-6526-4c39-8de0-d00d78ba5de0");
            
            /// <summary> Asset Path (Effects/RenderQuad.wefx) </summary>
            public static readonly Guid RenderQuad = new Guid("dfb5efbf-33e9-4b56-836d-cb8ca4ca0c80");
            
            /// <summary> Asset Path (Effects/SDFText.wefx) </summary>
            public static readonly Guid SDFText = new Guid("e6f51776-1e8e-449d-8fc4-c0a3a4e4de5c");
            
            /// <summary> Asset Path (Effects/SkyboxEffect.wefx) </summary>
            public static readonly Guid SkyboxEffect = new Guid("dd86a555-371c-4c72-8cf3-c32d5219af74");
            
            /// <summary> Asset Path (Effects/StandardEffect.wefx) </summary>
            public static readonly Guid StandardEffect = new Guid("daa1f60a-82ad-40fc-8fbb-7b85caa6de0a");
        }
        
        public sealed class Fonts
        {
            
            /// <summary> Asset Path (Fonts/Arial.ttf.weft) </summary>
            public static readonly Guid Arial_ttf = new Guid("d1322288-d9e9-4b1e-b2fe-ca281f0388a2");
        }
        
        public sealed class PostProcessingGraphs
        {
            
            /// <summary> Asset Path (PostProcessingGraphs/DefaultPostProcessingGraph.wepp) </summary>
            public static readonly Guid DefaultPostProcessingGraph = new Guid("dd593717-0922-4f58-9c85-c309658eff03");
        }
        
        public sealed class RenderLayers
        {
            
            /// <summary> Asset Path (RenderLayers/Additive.werl) </summary>
            public static readonly Guid Additive = new Guid("8e7317aa-3a55-45c6-82a5-47d333abe272");
            
            /// <summary> Asset Path (RenderLayers/Alpha.werl) </summary>
            public static readonly Guid Alpha = new Guid("e35c59a9-26ab-4b4c-8210-4b1f21c31530");
            
            /// <summary> Asset Path (RenderLayers/Opaque.werl) </summary>
            public static readonly Guid Opaque = new Guid("0db59561-b3f5-444f-b5de-e62e3a5b42bf");
            
            /// <summary> Asset Path (RenderLayers/Skybox.werl) </summary>
            public static readonly Guid Skybox = new Guid("da9e0221-f777-4e5a-96c2-df012f2d7bf2");
        }
        
        public sealed class Samplers
        {
            
            /// <summary> Asset Path (Samplers/LinearClampSampler.wesp) </summary>
            public static readonly Guid LinearClampSampler = new Guid("7d1e2792-2031-42bb-a67c-0dbd282be12a");
            
            /// <summary> Asset Path (Samplers/LinearWrapSampler.wesp) </summary>
            public static readonly Guid LinearWrapSampler = new Guid("9018edf8-ea96-4721-bf83-5561942432e0");
        }
    }
}
